# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addition.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_addition_window(object):
    def setupUi(self, addition_window):
        addition_window.setObjectName("addition_window")
        addition_window.resize(394, 138)
        self.btn_back_menu_2 = QtWidgets.QPushButton(addition_window)
        self.btn_back_menu_2.setGeometry(QtCore.QRect(260, 87, 116, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_back_menu_2.setFont(font)
        self.btn_back_menu_2.setObjectName("btn_back_menu_2")
        self.widget = QtWidgets.QWidget(addition_window)
        self.widget.setGeometry(QtCore.QRect(15, 80, 181, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_answer_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_answer_2.setFont(font)
        self.label_answer_2.setObjectName("label_answer_2")
        self.verticalLayout_3.addWidget(self.label_answer_2)
        self.txt_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_2.setFont(font)
        self.txt_2.setObjectName("txt_2")
        self.verticalLayout_3.addWidget(self.txt_2)
        self.widget1 = QtWidgets.QWidget(addition_window)
        self.widget1.setGeometry(QtCore.QRect(15, 10, 364, 64))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_a_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_a_2.setFont(font)
        self.number_a_2.setObjectName("number_a_2")
        self.verticalLayout.addWidget(self.number_a_2)
        self.number_b_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_b_2.setFont(font)
        self.number_b_2.setObjectName("number_b_2")
        self.verticalLayout.addWidget(self.number_b_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_answer_2 = QtWidgets.QPushButton(self.widget1)
        self.btn_answer_2.setObjectName("btn_answer_2")
        self.verticalLayout_2.addWidget(self.btn_answer_2)
        self.btn_next_2 = QtWidgets.QPushButton(self.widget1)
        self.btn_next_2.setObjectName("btn_next_2")
        self.verticalLayout_2.addWidget(self.btn_next_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(addition_window)
        self.btn_back_menu_2.clicked.connect(addition_window.close)
        QtCore.QMetaObject.connectSlotsByName(addition_window)

    def retranslateUi(self, addition_window):
        _translate = QtCore.QCoreApplication.translate
        self.random_a_2 = random.randint(10, 99)
        self.random_b_2 = random.randint(10, 99)
        self.answer_2 = self.random_a_2 + self.random_b_2
        self.number_a_2.setText(_translate("addition_window", "数字a:" + str(self.random_a_2)))
        self.number_b_2.setText(_translate("addition_window", "数字b:" + str(self.random_b_2)))
        self.btn_next_2.setHidden(True)
        self.btn_answer_2.setHidden(False)
        self.btn_answer_2.clicked.connect(self.check_2)
        addition_window.setWindowTitle(_translate("addition_window", "Form"))
        self.btn_back_menu_2.setText(_translate("addition_window", "返回菜单"))
        self.label_answer_2.setText(_translate("addition_window", "答案："))
        self.number_a_2.setText(_translate("addition_window", "数字a: " + str(self.random_a_2)))
        self.number_b_2.setText(_translate("addition_window", "数字b: " + str(self.random_b_2)))
        self.btn_answer_2.setText(_translate("addition_window", "提交"))
        self.btn_next_2.setText(_translate("addition_window", "下一题"))
        self.btn_next_2.clicked.connect(self.number_2)

    def number_2(self):
        _translate = QtCore.QCoreApplication.translate
        random_a_2 = random.randint(10, 99)
        random_b_2 = random.randint(10, 99)
        self.answer_2 = random_a_2 + random_b_2
        self.number_a_2.setText(_translate("addition_window", "数字a: " + str(random_a_2)))
        self.number_b_2.setText(_translate("addition_window", "数字b: " + str(random_b_2)))
        self.btn_next_2.setHidden(True)
        self.btn_answer_2.setHidden(False)


    def check_2(self):
        result = self.txt_2.text()
        try:
            if int(result) == int(self.answer_2):
                msg_box_1 = QMessageBox(QMessageBox.Warning, '恭喜你', '回答正确')
                msg_box_1.exec_()
                self.txt_2.clear()
                self.btn_next_2.setHidden(False)
                self.btn_answer_2.setHidden(True)


            else:
                msg_box_2 = QMessageBox(QMessageBox.Warning, '糟糕', '答案是错的')
                msg_box_2.exec_()
                self.txt_2.clear()
        except :
            msg_box_3 = QMessageBox(QMessageBox.Warning, '错误!', '有错误发生！')
            msg_box_3.exec_()
            self.txt_2.clear()
