# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Math_Test(object):
    def setupUi(self, Math_Test):
        Math_Test.setObjectName("Math_Test")
        Math_Test.resize(337, 328)
        self.centralwidget = QtWidgets.QWidget(Math_Test)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setGeometry(QtCore.QRect(70, 120, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_menu.setFont(font)
        self.btn_menu.setObjectName("btn_menu")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(250, 240, 83, 54))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.btn_about = QtWidgets.QPushButton(self.widget)
        self.btn_about.setObjectName("btn_about")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_about)
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setObjectName("btn_exit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_exit)
        Math_Test.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Math_Test)
        self.statusbar.setObjectName("statusbar")
        Math_Test.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Math_Test)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(Math_Test)
        self.btn_menu.clicked.connect(Math_Test.close)
        QtCore.QMetaObject.connectSlotsByName(Math_Test)

    def retranslateUi(self, Math_Test):
        _translate = QtCore.QCoreApplication.translate
        Math_Test.setWindowTitle(_translate("Math_Test", "MainWindow"))
        self.btn_menu.setText(_translate("Math_Test", "菜单"))
        self.btn_about.setText(_translate("Math_Test", "关于"))
        self.btn_exit.setText(_translate("Math_Test", "退出"))
        self.actionExit.setText(_translate("Math_Test", "Exit"))
